version: "3.7"

volumes:
  database_vol1:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn ${NODE_ENV}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - db
  
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    volumes:
      - database_vol1:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$TYPEORM_USERNAME"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s


